(deffacts BoardGames
	(game "Arcadia Quest")
	(game "Betrayal at House on the Hill")
	(game "Coup")
	(game "Dixit")
	(game "Dominion")
	(game "Galaxy Trucker")
	(game "Roll Through the Ages: The Bronze Age")
	(game "The Settlers of Catan")
	(game "Sheriff of Nottingham")
	(game "Small World")
	(game "Splendor")
	(game "Star Fluxx")
	(game "Ticket to Ride")
	(game "Shadows over Camelot")
	(game "Carcassonne")
	(game "Pandemic")
	(game "7 Wonders")
	(game "Codenames")
	(game "Hanabi")
	(game "Lords of Waterdeep")
	(game "Dead of Winter")
	(game "Five Tribes")
	(game "Star Realms")
	(game "Quadropolis")
	(game "Chaos in the Old World")
	(game "Bonanza")
	(game "Apples to Apples")
	(game "Secret Hitler")
	(game "Deception: Murder in Hong Kong")
	(game "Sushi Go!")
	(game "Alien Frontiers")
	(game "Clank")
)

(deffacts PlayerRange
	(player-range "Arcadia Quest" 2 4)
	(player-range "Betrayal at House on the Hill" 3 6)
	(player-range "Coup" 2 6)
	(player-range "Dixit" 3 6)
	(player-range "Dominion" 2 4)
	(player-range "Galaxy Trucker" 2 4)
	(player-range "Roll Through the Ages: The Bronze Age" 1 4)
	(player-range "The Settlers of Catan" 3 6)
	(player-range "Sheriff of Nottingham" 3 5)
	(player-range "Small World" 3 5)
	(player-range "Splendor" 2 4)
	(player-range "Star Fluxx" 2 6)
	(player-range "Ticket to Ride" 2 5)
	(player-range "Shadows over Camelot" 4 7)
	(player-range "Carcassonne" 2 5)
	(player-range "Pandemic" 2 4)
	(player-range "7 Wonders" 2 7)
	(player-range "Codenames" 2 8)
	(player-range "Hanabi" 2 5)
	(player-range "Lords of Waterdeep" 2 5)
	(player-range "Dead of Winter" 3 5)
	(player-range "Five Tribes" 2 4)
	(player-range "Star Realms" 2 2)
	(player-range "Quadropolis" 2 4)
	(player-range "Chaos in the Old World" 3 4)
	(player-range "Bonanza" 2 7)
	(player-range "Apples to Apples" 4 10)
	(player-range "Secret Hitler" 4 20)
	(player-range "Deception: Murder in Hong Kong" 5 10)
	(player-range "Sushi Go!" 3 8)
	(player-range "Alien Frontiers" 2 4)
	(player-range "Clank" 2 4)
)

