h0 = ["SF", "AA"]
h1 = ["DI", "RA", "BO", "SG"]
h2 = ["BH", "CP", "SE", "SN", "SP", "TR", "CA", "CO", "HA", "SH", "DE"]
h3 = ["DM", "GT", "SW", "SC", "PA", "WO", "LW", "FT", "SR", "QA", "AF", "CL"]
h4 = ["AQ", "DW", "CH"]

def codeGen(hardcoreness, codes):
  for code in codes:
    print('\n'.join([
      "",
      "(defrule Fam%s" % code,
      "  (valid-game %s)" % code,
      "  (GameLength %s)" % code,
      "  (GameFocus  %s)" % code,
      "  =>",
      "  (assert (Act %s)))" % hardcoreness,
    ]))

print("; FAMs are autogenerated code - see documentation")

codeGen("HA", h0)
codeGen("HB", h1)
codeGen("HC", h2)
codeGen("HD", h3)
codeGen("HE", h4)

print("\n; end of autogenerated code")
